# workflow name
name: Generate release-artifacts

# on events
on: [push]

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'bamboo-cctray'
            compress: 'true'
            dest: 'dist'
      - uses: actions/upload-artifact@v2
        with:
          name: windows-amd64
          path: dist/**/*windows-amd64.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: linux-amd64
          path: dist/**/*linux-amd64.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-amd64
          path: dist/**/*darwin-amd64.tar.gz
