# workflow name
name: Generate release-artifacts

# on events
on: [push]

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.17'
          check-latest: true
          cache: true
      - run: GOARCH=amd64 GOOS=linux go build -o bamboo-cctray-linux-amd64 .
      - run: GOARCH=arm64 GOOS=linux go build -o bamboo-cctray-linux-arm64 .
      - run: GOARCH=amd64 GOOS=windows go build -o bamboo-cctray-windows-amd64 .
      - run: GOARCH=amd64 GOOS=darwin go build -o bamboo-cctray-darwin-amd64 .
      - run: GOARCH=arm64 GOOS=darwin go build -o bamboo-cctray-darwin-arm64 .
      - uses: actions/upload-artifact@v2
        with:
          name: bamboo-cctray-windows-amd64
          path: bamboo-cctray-windows-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: bamboo-cctray-linux-amd64
          path: bamboo-cctray-linux-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: bamboo-cctray-linux-arm64
          path: bamboo-cctray-linux-arm64
      - uses: actions/upload-artifact@v2
        with:
          name: bamboo-cctray-darwin-amd64
          path: bamboo-cctray-darwin-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: bamboo-cctray-darwin-arm64
          path: bamboo-cctray-darwin-arm64
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bamboo-cctray-windows-amd64
            bamboo-cctray-linux-amd64
            bamboo-cctray-linux-arm64
            bamboo-cctray-darwin-amd64
            bamboo-cctray-darwin-arm64
